services:
  - type: web
    name: compassion-tracker
    env: node
    plan: free
    buildCommand: |
      # Create proper folder structure
      mkdir -p client/src/{components,hooks,lib,pages}
      mkdir -p server db shared scripts
      
      # Move files to correct locations
      mv index.html client/
      mv manifest.json client/
      mv App.tsx main.tsx index.css client/src/
      mv auth-page.tsx BloodPressure.tsx BowelMovements.tsx Calendar.tsx DeviceConnections.tsx Doctors.tsx EmergencyInfo.tsx GlucoseInsulin.tsx Home.tsx Meals.tsx Medications.tsx Notes.tsx NotificationSettings.tsx Pharmacies.tsx reset-password.tsx Sleep.tsx not-found.tsx client/src/pages/
      mv use-*.tsx client/src/hooks/
      mv queryClient.ts pinStorage.ts protected-route.tsx types.ts utils.ts client/src/lib/
      mv *Modal.tsx Dashboard.tsx Header.tsx BottomNavigation.tsx* CareRecipientTabs.tsx PageHeader.tsx StatusCard.tsx AddToDesktopButton.tsx character-count.tsx client/src/components/
      mv accordion.tsx alert*.tsx aspect-ratio.tsx avatar.tsx badge.tsx breadcrumb.tsx button.tsx card.tsx carousel.tsx chart.tsx checkbox.tsx collapsible.tsx command.tsx context-menu.tsx dialog.tsx drawer.tsx dropdown-menu.tsx form.tsx hover-card.tsx input*.tsx label.tsx menubar.tsx navigation-menu.tsx pagination.tsx popover.tsx progress.tsx radio-group.tsx resizable.tsx scroll-area.tsx select.tsx separator.tsx sheet.tsx sidebar.tsx skeleton.tsx slider.tsx switch.tsx table.tsx tabs.tsx textarea.tsx toast*.tsx toggle*.tsx tooltip.tsx client/src/components/
      mv index.ts vite.ts routes.ts* auth.ts email-service.ts notification-service.ts storage.ts types.d.ts webauthn.ts medicationService.ts server/
      mv schema.ts shared/
      mv seed*.ts init-database.js db/
      mv tables.sql scripts/
      
      # Install dependencies and build
      npm install
      npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: compassion-tracker-db
          property: connectionString

databases:
  - name: compassion-tracker-db
    databaseName: compassion_tracker
    user: compassion_user
    plan: free