services:
  - type: web
    name: compassion-tracker
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: compassion-tracker-db
          property: connectionString

databases:
  - name: compassion-tracker-db
    databaseName: compassion_tracker
    user: compassion_user
    plan: free